[book]
authors = ["DustVoice"]
language = "en"
multilingual = false
src = "src"
title = "DustWSL - DustVoice's WSL from scratch"

[preprocessor.alerts]

[output.html]
additional-css = ["devicon.min.css", "whichlang.css", "theme/catppuccin.css", "theme/catppuccin-alerts.css"]
additional-js = ["scripts/whichlang.js"]
default-theme = "macchiato"
preferred-dark-theme = "macchiato"
